# Remove the version line from here
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - worker
      - socket-service
    networks:
      - analyzer-net

  worker:
    build: ./backend/headlessBrowser-worker
    ports:
      - "8080:8080"
    environment:
      - CHROME_PATH=/usr/bin/google-chrome
    networks:
      - analyzer-net

  socket-service:
    build: ./backend/webSocket-server
    ports:
      - "8081:8081"
    networks:
      - analyzer-net

networks:
  analyzer-net:
    driver: bridge