services:
  # 1. React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      worker:
        condition: service_started
    networks:
      - analyzer-net

  # 2. WebSocket Socket Service
  socket-service:
    build: 
      context: . 
      dockerfile: ./backend/webSocket-server/Dockerfile
    ports:
      - "8081:8081"
    # Healthcheck: Try to hit the server. If it responds, it's healthy.
    healthcheck:
     # Use /health instead of /publish
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - analyzer-net

  # 3. Headless Go Worker
  worker:
    build: ./backend/headlessBrowser-worker
    ports:
      - "8080:8080"
    environment:
      - CHROME_PATH=/usr/bin/google-chrome
    # This tells Docker: Don't just start the worker, wait until socket-service is HEALTHY
    depends_on:
      socket-service:
        condition: service_healthy
    networks:
      - analyzer-net

networks:
  analyzer-net:
    driver: bridge